apiVersion: isoboot.io/v1alpha1
kind: BootTarget
metadata:
  name: debian-12-with-firmware
  labels:
    {{- include "isoboot.labels" . | nindent 4 }}
spec:
  bootMediaRef: debian-12
  useDebianFirmware: true
  template: |
{{ .Files.Get "files/boottarget-debian-v1.tpl" | indent 4 }}
