apiVersion: isoboot.io/v1alpha1
kind: BootTarget
metadata:
  name: debian-12-with-firmware
  labels:
    {{- include "isoboot.labels" . | nindent 4 }}
spec:
  files:
    - url: "https://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux"
      checksumURL: "https://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/SHA256SUMS"
    - url: "https://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz"
      checksumURL: "https://deb.debian.org/debian/dists/bookworm/main/installer-amd64/current/images/SHA256SUMS"
    - url: "https://cdimage.debian.org/cdimage/firmware/bookworm/current/firmware.cpio.gz"
      checksumURL: "https://cdimage.debian.org/cdimage/firmware/bookworm/current/SHA256SUMS"
  combinedFiles:
    - name: initrd.gz
      sources:
        - initrd.gz
        - firmware.cpio.gz
  template: |
{{ .Files.Get "files/boottarget-debian-v1.tpl" | indent 4 }}
