apiVersion: isoboot.io/v1alpha1
kind: BootTarget
metadata:
  name: debian-12-no-firmware
  labels:
    {{- include "isoboot.labels" . | nindent 4 }}
spec:
  bootSourceRef: debian-12
  useFirmware: false
  template: |
{{ .Files.Get "files/boottarget-debian-v1.tpl" | indent 4 }}
