apiVersion: isoboot.io/v1alpha1
kind: BootTarget
metadata:
  name: debian-13-no-firmware
  labels:
    {{- include "isoboot.labels" . | nindent 4 }}
spec:
  files:
    - url: "https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/netboot/debian-installer/amd64/linux"
      checksumURL: "https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/SHA256SUMS"
    - url: "https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/netboot/debian-installer/amd64/initrd.gz"
      checksumURL: "https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/SHA256SUMS"
  template: |
{{ .Files.Get "files/boottarget-debian-v1.tpl" | indent 4 }}
