apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "isoboot.fullname" . }}-templates
  labels:
    {{- include "isoboot.labels" . | nindent 4 }}
data:
  debian-13.ipxe: |
    {{- .Files.Get "files/debian-13.ipxe" | nindent 4 }}
