apiVersion: isoboot.io/v1alpha1
kind: DiskImage
metadata:
  name: debian-13
  labels:
    {{- include "isoboot.labels" . | nindent 4 }}
spec:
  iso: "https://deb.debian.org/debian/dists/trixie/main/installer-amd64/current/images/netboot/mini.iso"
  firmware: "https://cdimage.debian.org/cdimage/firmware/trixie/current/firmware.cpio.gz"
