apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ include "isoboot.fullname" . }}-macvlan
  labels:
    {{- include "isoboot.labels" . | nindent 4 }}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "{{ required "interface is required (e.g., --set interface=br1)" .Values.interface }}",
      "mode": "bridge",
      "ipam": {
        "type": "dhcp"
      }
    }
