apiVersion: v1
kind: Service
metadata:
  name: {{ include "isoboot.fullname" . }}-http
  labels:
    {{- include "isoboot.labels" . | nindent 4 }}
    app.kubernetes.io/component: http
spec:
  type: ClusterIP
  selector:
    {{- include "isoboot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: http
  ports:
    - port: {{ .Values.http.listenPort }}
      targetPort: {{ .Values.http.listenPort }}
      protocol: TCP
      name: http
